[crDroid]
l4t=1
boot_prefixes=switchroot/android/
id=SWANDR
icon=switchroot/android/icon_android_hue.bmp
logopath=switchroot/android/bootlogo_android.bmp
r2p_action=self
; alarms_disable=1 uncomment to disable notifications for better battery life
; touch_skip_tuning=1 uncomment if your touchscreen is broken
; usb3_enable=1 uncomment for faster USB at expense of WiFi/BT quality
; ddr200_enable=1 uncomment for faster SD speed on models that support it (Samsung enabled by default)
; emmc=1 uncomment for eMMC boot (internal storage, not recommended)
